### ISSUE TITLE
Got this error when `hsd` gets an AXFR request from ISC's `bind`

### ISSUE THREAD

**Issue by james-stevens** [buffrr/hsd-axfr#1] opened 2021-10-19 16:08 UTC
```
[info] (net) Received 16 addrs (hosts=205, peers=8) (40.113.229.250:12038).
[error] (ns) Out of bounds read (offset=32).
    at BufferReader.readU32BE (/opt/hsd-orig/node_modules/bufio/lib/reader.js:256:10)
    at EXPIREOption.read (/opt/hsd-orig/node_modules/bns/lib/wire.js:5825:22)
    at Function.read (/opt/hsd-orig/node_modules/bufio/lib/struct.js:143:23)
    at readOption (/opt/hsd-orig/node_modules/bns/lib/wire.js:6620:27)
    at Option.read (/opt/hsd-orig/node_modules/bns/lib/wire.js:5441:19)
    at Function.read (/opt/hsd-orig/node_modules/bufio/lib/struct.js:143:23)
    at OPTRecord.read (/opt/hsd-orig/node_modules/bns/lib/wire.js:3788:32)
    at Function.read (/opt/hsd-orig/node_modules/bufio/lib/struct.js:143:23)
    at readData (/opt/hsd-orig/node_modules/bns/lib/wire.js:6513:24)
    at Record.read (/opt/hsd-orig/node_modules/bns/lib/wire.js:1885:17)
[info] (axfr) [127.0.0.1:47597]  Starting zone transfer
```

My guess would be `bind` is sending some extra records at the end of the `AXFR` request, like an `EDNS0` or `DNS Cookie` or something. The transfer then seems to start fine - but its ducking slow as heck, so still waiting for it to complete.

BTW: would be *REALLY* nice if the SOA Serial reflected the version of the data, instead of just giving the current date & time - that way I could run two copies of `hsd` and pull the zone file from either & if one had been down and was still catching up, `bind` wouldn't end up pulling stale data from it.

If you are pulling the `AXFR` from the frozen data, instead of the live data (this is the preferred choice but sorry, I don't know your terminology for these two data sets), the SOA Serial should reflect the "version" of the frozen data, e.g. the unix timestamp of the last packet that got included or something.

**Comment by james-stevens** [comment] 2021-10-19 16:46
Run with ` ./bin/hsd --prefix=/opt/hsd-data/ --plugins=$(pwd)/axfr --axfr-icann-servers='192.33.4.12 199.9.14.201 192.5.5.241'`

Now I can see `debug` messages `AXFR` ends
```
[warning] (ns) Root server middleware resolution failed for name: .
[debug] (ns) Error: Unknown serialization version: 2.
    at Resource.read (/opt/hsd-orig/lib/dns/resource.js:117:13)
    at Resource.decode (/opt/hsd-orig/node_modules/bufio/lib/struct.js:94:10)
    at Function.decode (/opt/hsd-orig/node_modules/bufio/lib/struct.js:147:23)
    at Plugin.sendAXFR (/opt/hsd-orig/axfr/lib/axfr.js:162:33)
    at async RootServer.Plugin.ns.middle (/opt/hsd-orig/axfr/lib/axfr.js:74:16)
    at async RootServer.resolve (/opt/hsd-orig/lib/dns/server.js:486:15)
    at async RootServer.answer (/opt/hsd-orig/node_modules/bns/lib/server/dns.js:249:17)
    at async RootServer.handle (/opt/hsd-orig/node_modules/bns/lib/server/dns.js:316:13)
    at async Server.<anonymous> (/opt/hsd-orig/node_modules/bns/lib/server/dns.js:72:9)
[debug] (net) Requesting 1/1 txs from peer with getdata (159.69.46.23:12038).
```
Interestingly, this serialization error was actually what stopped my `zone-dump` from working.
```
    if (version !== 0)
      throw new Error(`Unknown serialization version: ${version}.`);
```
Not exactly sure why an `error` is only showing up in `debug`

Now the AXFR data ends
```
fastestshipper.         21600   IN      NS      ns1.fastestshipper.
fastestshipper.         21600   IN      NS      ns2.fastestshipper.
.                       86400   IN      SOA     . . 2021101916 1800 900 604800 21600
.                       0       ANY     SIG     0 253 0 0 20211019223904 20211019103904 41555 . 3ekJC/2vq261JARHDxHMQn4I88JsivgweN/K4rLzvZZowyDw1GBWqxA/ V74iHPORosQik6TcbwgGPhOBUblPLg==
; Transfer failed.
```
Still no ICANN domains in the data

**Comment by buffrr** [comment] 2021-10-19 23:20
> My guess would be bind is sending some extra records at the end of the AXFR request, like an EDNS0 or DNS Cookie or something.

Ugh i'm not a big fan of bns you're probably right will look into this but the last time I tested with bind it worked fine.

I was able to reproduce this issue. I wrapped Resource.decode in a try/catch block and the name `roivantsciences` is what's causing the serialization error.

Trying to dig this name `dig @127.0.0.1 -p 5349 roivantsciences` i can see the serialization error/servfail. I will submit a fix for this but i was able to export it after catching the error:

root zone is much larger now :) it took approx 6 minutes to export.

```
$ tail root.zone
ns1zim.telone.co.zw.    172800  IN      AAAA    2c0f:f758:0:a::81
ns1zim.telone.co.zw.    172800  IN      A       41.220.30.81
ns2zim.telone.co.zw.    172800  IN      AAAA    2c0f:f758:0:a::82
ns2zim.telone.co.zw.    172800  IN      A       41.220.30.82
.                       86400   IN      SOA     . . 2021101923 1800 900 604800 21600
;; Query time: 351320 msec
;; SERVER: 127.0.0.1#5349(127.0.0.1)
;; WHEN: Tue Oct 19 16:06:00 MST 2021
;; XFR size: 4615594 records (messages 2396, bytes 132724457)
```

> BTW: would be REALLY nice if the SOA Serial reflected the version of the data, instead of just giving the current date & time - that way I could run two copies of hsd and pull the zone file from either & if one had been down and was still catching up, bind wouldn't end up pulling stale data from it.

Yup, I'd like to add this. Also, would be nice if the user can specify the NS records serving the root zone (if u r running public resolver). For example, I have the name `root-servers/` and would like to add `. NS a.root-servers`, `. NS b.root-servers` ... etc to the exported zone (obv depends on the number of root servers u r running). Instead of `. NS .` or synth records so things like `dig . +trace works`. SOA should have correct primary server too.

> If you are pulling the AXFR from the frozen data, instead of the live data (this is the preferred choice but sorry, I don't know your terminology for these two data sets), the SOA Serial should reflect the "version" of the frozen data, e.g. the unix timestamp of the last packet that got included or something.

I believe it's using the "frozen" data but unfortunately there's a chance it could change during chain [re-organization](https://en.bitcoin.it/wiki/Chain_Reorganization). The older the data the less likely it's affected by a reorg so we may want to wait a few blocks to make the serial more reliable.  

> NOTE: I was running with options --ns-host 127.0.0.9 --ns-port 53 - will try again with no port or IP options, as per instructions, but I would REALLY prefer to be able to use them.

you should be able to use this option.

> Still no ICANN domains in the data

Any names with collisions should be replaced during transfer but remaining ICANN TLDs like .com,.net ... etc are appended at the end of the zone file but because the transfer is failing you're not seeing them yet.

BTW, you should use HSD v3 it has `--no-sig0` option. I'm currently using it this way which disables recursive resolver, wallet plugin and sig0. Runs the root server only:

```
./bin/hsd --no-wallet --no-rs --no-sig0 --plugins=$(pwd)/hsd-axfr 
```

**Comment by james-stevens** [comment] 2021-11-12 17:28
> Root KSK could end up becoming an obsolete concept in Handshake

I _**really**_ like this idea as well as the idea of distributing the ROOT by blockchain, instead of having centralised ROOT servers.. Having the TLD's DS pre-validated from the blockchain should significantly improve the performance of DNSSEC validation, as neither the TLD nor the ROOT need to be validated.

However, would be even nicer if the ICANN TLDs were also in the blockchain. IMHO some will claim their TLD, but many won't, out of loyalty to ICANN, like Verisign. So either you'd need to have some daemon process that inserts those TLDs for them, or fall-back to ICANN's KSK, which is a shame, but perfectly reasonable.

Mike told me about the browser work you've done - that's really cool, nice one.


You may as well close this "issue". Thank you so much for all your help.

**Comment by buffrr** [comment] 2021-11-13 01:32
> its a validating resolver & provides [A/I]XFR of the signed ROOT, people can run their own container of it from here -> https://github.com/james-stevens/handshake-resolver or here https://hub.docker.com/r/jamesstevens/handshake-resolver

Ha cool! sorry I was quite busy and didn't get a chance to look into this repo. We'll see if I can get a HIP-5 server up and running to optionally replace ._eth NS records in the exported zone.

> Mike told me about the browser work you've done - that's really cool, nice one.

Thanks! getting hnsd to work reliably on mobile and doing DNSSEC validation with very limited CPU time is very tricky. The desktop version will be significantly easier. 

> You may as well close this "issue". Thank you so much for all your help.

I updated the plugin to fix the problems in this issue so you no longer need to patch it.

**Closed by buffrr** 2021-11-13 01:32 UTC
